//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metric_Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metric_Designer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xs:element name=&quot;issue&quot;&gt;
        ///        &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///                &lt;xs:element minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot; ref=&quot;issue&quot;/&gt;
        ///            &lt;/xs:sequence&gt;
        ///            &lt;xs:attribute name=&quot;type&quot; type=&quot;xs:string&quot;/&gt;
        ///            &lt;xs:attribute name=&quot;name&quot; type=&quot;xs:string&quot;/&gt;
        ///            &lt;xs:attribute name=&quot;level&quot; type=&quot;xs:nonNegativeInteger&quot;/&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metricSchema {
            get {
                return ResourceManager.GetString("metricSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xs:element name=&quot;description&quot; type=&quot;xs:string&quot;/&gt;
        ///    &lt;xs:element name=&quot;examples&quot; type=&quot;xs:string&quot;/&gt;
        ///    &lt;xs:element name=&quot;notes&quot; type=&quot;xs:string&quot;/&gt;
        ///    &lt;xs:element name=&quot;errorType&quot;&gt;
        ///        &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///                &lt;xs:element minOccurs=&quot;0&quot; ref=&quot;description&quot;/&gt;
        ///                &lt;xs:element minOccurs=&quot;0&quot; ref=&quot;notes&quot;/&gt;
        ///                &lt;xs: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string typologySchema {
            get {
                return ResourceManager.GetString("typologySchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    exclude-result-prefixes=&quot;xs&quot;
        ///    version=&quot;2.0&quot;&gt;
        ///    &lt;xsl:template match=&quot;/&quot;&gt;
        ///        &lt;issues&gt;
        ///            &lt;xsl:apply-templates/&gt;
        ///        &lt;/issues&gt;
        ///    &lt;/xsl:template&gt;
        ///    &lt;xsl:template match=&quot;errorType&quot;&gt;
        ///        &lt;issue display=&quot;yes&quot; weight=&quot;1&quot;&gt;
        ///            &lt;xsl:attribute name=&quot;type&quot;&gt;
        ///                &lt;xsl:value-of select=&quot;./@id&quot;/&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string typologyToMetric {
            get {
                return ResourceManager.GetString("typologyToMetric", resourceCulture);
            }
        }
    }
}
