# A GitHub Actions workflow that build and releases the .NET 8 application when a new tag is pushed to "main" branch.
name: Build and Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Build with dotnet
      run: dotnet build --configuration Release

    # - name: Test with dotnet
    #   run: dotnet test --no-restore --verbosity normal

    - name: Publish with dotnet
      run: dotnet publish -c Release -o ./publish /p:Version=${{ github.ref == 'refs/heads/main' && '0.0.0' || github.ref.replace('refs/tags/v', '') }}


    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release


  release:
    needs: build
    runs-on: ubuntu-latest

    # only if not workflow_dispatch
    if: github.event_name == 'push'

    steps:
    - name: Download production artifacts
      uses: actions/download-artifact@v4
      with:
        name: release

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./publish/**.exe
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Release
